mow_area:
  target:
    entity:
      domain: lawn_mower
      integration: ecovacs_mower
  fields:
    area_ids:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 999
          step: 1
          mode: box
          multiple: true
